#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import os.path
import subprocess
import uuid
import time
import json
import urllib
import urllib2

def gethome():
	return os.path.expanduser('~')

def getqueuepath():
	return os.path.join(gethome(), '.clog-queue')

def runqueue(server):
	print("starting queue dispatch...")
	qp = getqueuepath()
	os.chdir(qp)
	for f in os.listdir('.'):
		if len(f) == 41 and f.endswith('.meta'):
			rid = f[:36]
			print("sending job {}...").format(rid)
			with open(f, 'r') as fp:
				meta = json.load(fp)
			with open(rid + '.log', 'r') as fp:
				meta['output'] = fp.read()
			meta['id'] = rid
			req = urllib.urlencode(meta)
			res = urllib2.urlopen(server, req)
			os.unlink("{}.log".format(rid))
			os.unlink("{}.meta".format(rid))
	print("finished queue dispatch")


if __name__ == '__main__':

	if len(sys.argv) > 1:
		server = sys.argv[1]
		runqueue(server)
	else:
		print("Usage: {} <server url>").format(sys.argv[0])
		sys.exit(1)