#!/usr/bin/env python
# -*- coding: utf-8 -*-

import tornado.ioloop
import tornado.web
import sqlite3
import os

class Jobs(tornado.web.RequestHandler):

	def post(self):
		script = self.get_argument('script')
		self.write('ok')

application = tornado.web.Application([
	(r"/jobs", Jobs),
], debug=True)

if __name__ == '__main__':
	if not os.path.isdir('outputs'):
		os.mkdir('outputs', 0700)
	application.listen(7890)
	tornado.ioloop.IOLoop.instance().start()