#!/usr/bin/env python
# -*- coding: utf-8 -*-

import sys
import os
import os.path
import subprocess
import uuid
import time
import json

def gethome():
	return os.path.expanduser('~')

def getqueuepath():
	return os.path.join(gethome(), '.clog-queue')

def runqueue():
	print("starting queue dispatch...")
	qp = getqueuepath()
	os.chdir(qp)
	for f in os.listdir('.'):
		if len(f) == 41 and f.endswith('.meta'):
			rid = f[:36]
			print("sending job {}...").format(rid)
			os.unlink("{}.log".format(rid))
			os.unlink("{}.meta".format(rid))
	print("finished queue dispatch")


if __name__ == '__main__':
	runqueue()